# Generated by Django 5.2.6 on 2026-08-02

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def conserver_valeur_anciens_biens(apps, schema_editor):
    BienEtablissement = apps.get_model('depenses', 'BienEtablissement')
    for bien in BienEtablissement.objects.filter(
        prix_achat_unitaire=0,
        valeur_acquisition__gt=0,
    ).iterator():
        bien.prix_achat_unitaire = bien.valeur_acquisition
        bien.save(update_fields=['prix_achat_unitaire'])


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0007_logistique_bibliotheque_sync_tracking'),
        ('eleves', '0016_ecole_bonus_suivi_actif'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bienetablissement',
            name='prix_achat_unitaire',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=15, verbose_name="Prix d'achat unitaire (GNF)"),
        ),
        migrations.AddField(
            model_name='bienetablissement',
            name='quantite_achetee',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité achetée'),
        ),
        migrations.AddField(
            model_name='bienetablissement',
            name='quantite_gatee',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité gâtée/perdue'),
        ),
        migrations.AddField(
            model_name='bienetablissement',
            name='quantite_utilisee',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité utilisée'),
        ),
        migrations.AddField(
            model_name='bienetablissement',
            name='unite_mesure',
            field=models.CharField(choices=[('PIECE', 'Pièce'), ('BOITE', 'Boîte'), ('PAQUET', 'Paquet'), ('RAME', 'Rame'), ('CARTON', 'Carton'), ('LOT', 'Lot')], default='PIECE', max_length=20, verbose_name='Unité'),
        ),
        migrations.RunPython(conserver_valeur_anciens_biens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='bienetablissement',
            name='type_bien',
            field=models.CharField(choices=[('SALLE_CLASSE', 'Salle de classe'), ('BUREAU', 'Bureau'), ('LABORATOIRE', 'Laboratoire'), ('BIBLIOTHEQUE', 'Bibliothèque'), ('TOILETTE', 'Toilette'), ('CANTINE', 'Cantine'), ('TERRAIN_SPORT', 'Terrain de sport'), ('COUR', 'Cour'), ('PARKING', 'Parking'), ('TABLE', 'Table(s)'), ('CHAISE', 'Chaise(s)'), ('ARMOIRE', 'Armoire'), ('ETAGERE', 'Étagère'), ('CLIMATISEUR', 'Climatiseur'), ('ORDINATEUR', 'Ordinateur'), ('IMPRIMANTE', 'Imprimante'), ('PROJECTEUR', 'Projecteur'), ('TABLEAU', 'Tableau'), ('GLOBE_TERRESTRE', 'Globe terrestre'), ('CARTE', 'Carte géographique'), ('COMPAS', 'Compas'), ('EQUERRE', 'Équerre'), ('MARQUEUR', 'Marqueur(s)'), ('FOURNITURE', 'Fourniture(s)'), ('AMPOULE', 'Ampoule(s)'), ('VENTILATEUR', 'Ventilateur'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type de bien'),
        ),
        migrations.CreateModel(
            name='ContributionPapierRame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
                ('sync_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('type_contribution', models.CharField(choices=[('PAPIER', 'Papier RAM envoyé'), ('ARGENT', 'Argent payé à la place')], max_length=10, verbose_name='Mode de contribution')),
                ('nombre_paquets', models.PositiveIntegerField(default=0, verbose_name='Nombre de paquets/rames')),
                ('montant_paye', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=15, verbose_name='Montant payé (GNF)')),
                ('date_contribution', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions_papier_rame_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions_papier_rame', to='eleves.eleve', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Contribution papier RAM',
                'verbose_name_plural': 'Contributions papier RAM',
                'ordering': ['-date_contribution', '-date_creation'],
                'indexes': [models.Index(fields=['eleve', 'date_contribution'], name='depenses_co_eleve_i_6f4a35_idx'), models.Index(fields=['type_contribution', 'date_contribution'], name='depenses_co_type_co_548c63_idx')],
            },
        ),
    ]
