# Generated by Django 5.2.6 on 2026-08-05 12:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0009_fournitures_scolaires'),
        ('eleves', '0016_ecole_bonus_suivi_actif'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonnementInformatique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
                ('sync_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, help_text="Renseignée automatiquement à l'enregistrement.", verbose_name="Date d'enregistrement")),
                ('montant', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name="Montant de l'abonnement (GNF)")),
                ('date_debut', models.DateField(default=django.utils.timezone.localdate, verbose_name='Début')),
                ('date_fin', models.DateField(db_index=True, verbose_name='Fin')),
                ('alerte_avant_jours', models.PositiveIntegerField(default=7, help_text="Nombre de jours avant la fin à partir duquel l'abonnement est signalé.", verbose_name='Alerte avant (jours)')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('RESILIE', 'Résilié')], db_index=True, default='ACTIF', max_length=10, verbose_name='Statut')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements_informatique', to='eleves.eleve', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Abonnement informatique',
                'verbose_name_plural': 'Abonnements informatiques',
                'ordering': ['-date_fin', 'eleve__nom'],
            },
        ),
        migrations.CreateModel(
            name='DepenseCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
                ('sync_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, help_text="Renseignée automatiquement à l'enregistrement.", verbose_name='Date')),
                ('montant', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Montant (GNF)')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='eleves.ecole', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Dépense de cuisine',
                'verbose_name_plural': 'Dépenses de cuisine',
                'ordering': ['-date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DepenseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
                ('sync_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, help_text="Renseignée automatiquement à l'enregistrement.", verbose_name='Date')),
                ('montant', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Montant (GNF)')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='eleves.ecole', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Dépense de document',
                'verbose_name_plural': 'Dépenses de documents',
                'ordering': ['-date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Versement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
                ('sync_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, help_text="Renseignée automatiquement à l'enregistrement.", verbose_name='Date')),
                ('montant', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Montant (GNF)')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lieu_versement', models.CharField(max_length=200, verbose_name='Lieu de versement')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='eleves.ecole', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Versement',
                'verbose_name_plural': 'Versements',
                'ordering': ['-date', '-id'],
                'abstract': False,
            },
        ),
    ]
