# Generated by Django 5.2.6 on 2026-08-05 10:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0009_article_prix_vente_unitaire'),
        ('eleves', '0016_ecole_bonus_suivi_actif'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepenseCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
                ('sync_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('montant', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Montant (GNF)')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_cuisine_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dépense cuisine',
                'verbose_name_plural': 'Dépenses cuisine',
                'ordering': ['-date', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='DepenseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
                ('sync_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('montant', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Montant (GNF)')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_document_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dépense document',
                'verbose_name_plural': 'Dépenses document',
                'ordering': ['-date', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Versement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
                ('sync_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date')),
                ('montant', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Montant (GNF)')),
                ('lieu_versement', models.CharField(max_length=200, verbose_name='Lieu de versement')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versements_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versement',
                'verbose_name_plural': 'Versements',
                'ordering': ['-date', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='AbonnementInformatique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
                ('sync_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('montant', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10, verbose_name="Montant d'abonnement (GNF)")),
                ('date_debut', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date de début')),
                ('date_fin', models.DateField(db_index=True, verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('SUSPENDU', 'Suspendu')], db_index=True, default='ACTIF', max_length=10)),
                ('alerte_avant_jours', models.PositiveIntegerField(default=7, verbose_name='Alerte avant (jours)')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonnements_informatique_crees', to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements_informatique', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Abonnement informatique',
                'verbose_name_plural': 'Abonnements informatique',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['eleve', 'statut'], name='depenses_ab_eleve_i_6e0175_idx'), models.Index(fields=['eleve', 'date_fin'], name='depenses_ab_eleve_i_0b66f5_idx'), models.Index(fields=['statut', 'date_fin'], name='depenses_ab_statut_95113d_idx')],
            },
        ),
    ]
