# Generated by Django 5.2.6 on 2026-08-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0010_abonnementinformatique_depensecuisine_and_more'),
        ('depenses', '0010_depensecuisine_depensedocument_versement_and_more'),
    ]

    operations = [
    ]
