# Generated by Django 5.2.6 on 2026-08-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0012_normaliser_schema_recouvrement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnementinformatique',
            name='alerte_avant_jours',
            field=models.PositiveIntegerField(default=7, verbose_name='Alerte avant (jours)'),
        ),
        migrations.AlterField(
            model_name='abonnementinformatique',
            name='date_fin',
            field=models.DateField(db_index=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='bienetablissement',
            name='type_bien',
            field=models.CharField(choices=[('SALLE_CLASSE', 'Salle de classe'), ('BUREAU', 'Bureau'), ('LABORATOIRE', 'Laboratoire'), ('BIBLIOTHEQUE', 'Bibliothèque'), ('TOILETTE', 'Toilette'), ('CANTINE', 'Cantine'), ('TERRAIN_SPORT', 'Terrain de sport'), ('COUR', 'Cour'), ('PARKING', 'Parking'), ('TABLE', 'Table(s)'), ('CHAISE', 'Chaise(s)'), ('ARMOIRE', 'Armoire'), ('ETAGERE', 'Étagère'), ('CLIMATISEUR', 'Climatiseur'), ('ORDINATEUR', 'Ordinateur'), ('IMPRIMANTE', 'Imprimante'), ('PROJECTEUR', 'Projecteur'), ('TABLEAU', 'Tableau'), ('GLOBE_TERRESTRE', 'Globe terrestre'), ('CARTE', 'Carte géographique'), ('COMPAS', 'Compas'), ('EQUERRE', 'Équerre'), ('MARQUEUR', 'Marqueur(s)'), ('FOURNITURE', 'Fourniture(s)'), ('AMPOULE', 'Ampoule(s)'), ('VENTILATEUR', 'Ventilateur'), ('FOURNITURE', 'Fourniture'), ('MARQUEUR', 'Marqueur(s)'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type de bien'),
        ),
    ]
