# Generated by Django 5.2.6 on 2026-08-10 07:48

import ecole_moderne.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0016_ecole_bonus_suivi_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='annee_scolaire',
            field=models.CharField(help_text='Format: 2024-2025', max_length=9, validators=[ecole_moderne.validators.valider_annee_scolaire], verbose_name='Année scolaire'),
        ),
        migrations.AlterField(
            model_name='grilletarifaire',
            name='annee_scolaire',
            field=models.CharField(max_length=9, validators=[ecole_moderne.validators.valider_annee_scolaire], verbose_name='Année scolaire'),
        ),
    ]
