# Generated by Django 5.2.6 on 2026-08-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0016_ecole_bonus_suivi_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='niveau',
            field=models.CharField(choices=[('GARDERIE', 'Garderie'), ('TOUTE_PETITE_SECTION', 'Toute petite section'), ('PETITE_SECTION', 'Petite section'), ('MOYENNE_SECTION', 'Moyenne section'), ('GRANDE_SECTION', 'Grande section'), ('MATERNELLE', 'Maternelle (ancienne appellation)'), ('PRIMAIRE_1', 'Primaire 1ère'), ('PRIMAIRE_2', 'Primaire 2ème'), ('PRIMAIRE_3', 'Primaire 3ème'), ('PRIMAIRE_4', 'Primaire 4ème'), ('PRIMAIRE_5', 'Primaire 5ème'), ('PRIMAIRE_6', 'Primaire 6ème'), ('COLLEGE_7', 'Collège 7ème'), ('COLLEGE_8', 'Collège 8ème'), ('COLLEGE_9', 'Collège 9ème'), ('COLLEGE_10', 'Collège 10ème'), ('LYCEE_11', 'Lycée 11ème'), ('LYCEE_12', 'Lycée 12ème'), ('TERMINALE', 'Terminale')], max_length=20, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='grilletarifaire',
            name='niveau',
            field=models.CharField(choices=[('GARDERIE', 'Garderie'), ('TOUTE_PETITE_SECTION', 'Toute petite section'), ('PETITE_SECTION', 'Petite section'), ('MOYENNE_SECTION', 'Moyenne section'), ('GRANDE_SECTION', 'Grande section'), ('MATERNELLE', 'Maternelle (ancienne appellation)'), ('PRIMAIRE_1', 'Primaire 1ère'), ('PRIMAIRE_2', 'Primaire 2ème'), ('PRIMAIRE_3', 'Primaire 3ème'), ('PRIMAIRE_4', 'Primaire 4ème'), ('PRIMAIRE_5', 'Primaire 5ème'), ('PRIMAIRE_6', 'Primaire 6ème'), ('COLLEGE_7', 'Collège 7ème'), ('COLLEGE_8', 'Collège 8ème'), ('COLLEGE_9', 'Collège 9ème'), ('COLLEGE_10', 'Collège 10ème'), ('LYCEE_11', 'Lycée 11ème'), ('LYCEE_12', 'Lycée 12ème'), ('TERMINALE', 'Terminale')], max_length=20, verbose_name='Niveau'),
        ),
    ]
