# Generated by Django 5.2.6 on 2026-08-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0017_alter_classe_annee_scolaire_and_more'),
        ('eleves', '0017_alter_classe_niveau_alter_grilletarifaire_niveau'),
    ]

    operations = [
    ]
