# Generated by Django 5.2.6 on 2026-08-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0018_merge_20260829_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='annee_scolaire',
            field=models.CharField(help_text='Format: 2024-2025', max_length=9, verbose_name='Année scolaire'),
        ),
        migrations.AlterField(
            model_name='grilletarifaire',
            name='annee_scolaire',
            field=models.CharField(max_length=9, verbose_name='Année scolaire'),
        ),
    ]
