# Generated by Django 5.2.6 on 2026-09-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0019_ecole_couleurs_cartes'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='import_verrouille',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name="Import verrouillé jusqu'au premier paiement validé"),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('ATTENTE_PAIEMENT', 'Verrouillé — premier paiement attendu'), ('SUSPENDU', 'Suspendu'), ('EXCLU', 'Exclu'), ('TRANSFERE', 'Transféré'), ('DIPLOME', 'Diplômé')], db_index=True, default='ACTIF', max_length=20, verbose_name='Statut'),
        ),
    ]
