# Generated by Django 5.2.17 on 2026-09-22 17:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0020_import_verrouille_premier_paiement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LienCollecteEleves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('annee_scolaire', models.CharField(max_length=9)),
                ('destinataire', models.CharField(max_length=150, verbose_name='Enseignant destinataire')),
                ('expire_le', models.DateTimeField(verbose_name="Valable jusqu'au")),
                ('revoque_le', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_collecte', to='eleves.classe')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_collecte', to='eleves.ecole')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='EnvoiCollecteEleves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.UUIDField()),
                ('auteur', models.CharField(max_length=150, verbose_name='Votre nom')),
                ('recu_le', models.DateTimeField(auto_now_add=True)),
                ('lien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envois', to='eleves.liencollecteeleves')),
            ],
            options={
                'ordering': ['-recu_le', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PropositionEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100, verbose_name="Prénom de l'élève")),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'élève")),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, verbose_name='Lieu de naissance')),
                ('prenom_responsable', models.CharField(blank=True, max_length=100, verbose_name='Prénom du responsable')),
                ('nom_responsable', models.CharField(blank=True, max_length=100, verbose_name='Nom du responsable')),
                ('telephone_responsable', models.CharField(blank=True, max_length=20, verbose_name='Téléphone du responsable')),
                ('adresse', models.CharField(blank=True, max_length=300, verbose_name='Adresse')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'À vérifier'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], db_index=True, default='EN_ATTENTE', max_length=12)),
                ('traite_le', models.DateTimeField(blank=True, null=True)),
                ('eleve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eleves.eleve')),
                ('envoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to='eleves.envoicollecteeleves')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddIndex(
            model_name='liencollecteeleves',
            index=models.Index(fields=['ecole', 'cree_le'], name='collecte_ecole_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='envoicollecteeleves',
            constraint=models.UniqueConstraint(fields=('lien', 'identifiant'), name='collecte_envoi_unique'),
        ),
    ]
