# Generated by Django 5.2.6 on 2026-08-09 08:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_systemlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorbeilleEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleve_id_origine', models.PositiveIntegerField(db_index=True, verbose_name="ID d'origine")),
                ('matricule', models.CharField(db_index=True, max_length=50)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('classe_nom', models.CharField(blank=True, max_length=150)),
                ('ecole_nom', models.CharField(blank=True, max_length=200)),
                ('annee_scolaire', models.CharField(blank=True, max_length=9)),
                ('donnees', models.JSONField(blank=True, default=dict, verbose_name='Instantané des données')),
                ('motif', models.TextField(blank=True, verbose_name='Motif de la suppression')),
                ('date_suppression', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('restaure', models.BooleanField(db_index=True, default=False)),
                ('date_restauration', models.DateTimeField(blank=True, null=True)),
                ('restaure_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves_restaures', to=settings.AUTH_USER_MODEL)),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves_mis_corbeille', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Élève en corbeille',
                'verbose_name_plural': 'Corbeille des élèves',
                'ordering': ['-date_suppression'],
            },
        ),
        migrations.CreateModel(
            name='JournalModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_index=True, max_length=100)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('objet_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('objet_repr', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('RESTAURATION', 'Restauration')], db_index=True, default='MODIFICATION', max_length=20)),
                ('changements', models.JSONField(blank=True, default=dict)),
                ('commentaire', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('date_modification', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('annule', models.BooleanField(db_index=True, default=False)),
                ('date_annulation', models.DateTimeField(blank=True, null=True)),
                ('annule_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications_annulees', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications_journal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modification (corbeille mémoire)',
                'verbose_name_plural': 'Corbeille mémoire des modifications',
                'ordering': ['-date_modification'],
                'indexes': [models.Index(fields=['app_label', 'model_name', 'objet_id'], name='administrat_app_lab_a54d7f_idx')],
            },
        ),
    ]
