# Generated by Django 5.2.6 on 2026-08-09 06:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_systemlog_action'),
        ('eleves', '0016_ecole_bonus_suivi_actif'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementCorbeille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('SUPPRESSION', 'Suppression'), ('MODIFICATION', 'Modification')], db_index=True, max_length=15)),
                ('model_label', models.CharField(db_index=True, help_text='Ex: eleves.Eleve', max_length=120)),
                ('objet_id', models.PositiveIntegerField(blank=True, null=True)),
                ('libelle', models.CharField(max_length=255, verbose_name='Élément')),
                ('donnees_avant', models.JSONField(blank=True, default=dict)),
                ('donnees_apres', models.JSONField(blank=True, default=dict)),
                ('champs_modifies', models.JSONField(blank=True, default=list)),
                ('objets_lies', models.JSONField(blank=True, default=list)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('restaure', models.BooleanField(db_index=True, default=False)),
                ('date_restauration', models.DateTimeField(blank=True, null=True)),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements_corbeille', to='eleves.ecole')),
                ('restaure_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements_corbeille_restaures', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Élément de la corbeille',
                'verbose_name_plural': 'Corbeille',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['type_operation', 'restaure', '-date'], name='administrat_type_op_d7dc5a_idx'), models.Index(fields=['model_label', 'objet_id'], name='administrat_model_l_1688a7_idx')],
            },
        ),
    ]
