# Generated by Django 5.2.6 on 2026-08-09 11:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_corbeilleeleve_journalmodification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorbeilleElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_index=True, max_length=100)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('modele_libelle', models.CharField(blank=True, max_length=150, verbose_name="Type d'objet")),
                ('objet_id_origine', models.PositiveIntegerField(db_index=True, verbose_name="ID d'origine")),
                ('objet_repr', models.CharField(blank=True, max_length=255)),
                ('contexte', models.CharField(blank=True, max_length=255, verbose_name='Élève / rattachement')),
                ('ecole_nom', models.CharField(blank=True, max_length=200)),
                ('donnees', models.JSONField(blank=True, default=dict, verbose_name='Instantané des données')),
                ('motif', models.TextField(blank=True)),
                ('date_suppression', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('restaure', models.BooleanField(db_index=True, default=False)),
                ('date_restauration', models.DateTimeField(blank=True, null=True)),
                ('restaure_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements_restaures', to=settings.AUTH_USER_MODEL)),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements_mis_corbeille', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Élément en corbeille',
                'verbose_name_plural': 'Corbeille des éléments supprimés',
                'ordering': ['-date_suppression'],
                'indexes': [models.Index(fields=['app_label', 'model_name'], name='administrat_app_lab_1cef1e_idx')],
            },
        ),
    ]
