# Generated by Django 5.2.6 on 2026-08-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_elementcorbeille'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementcorbeille',
            name='motif',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motif'),
        ),
    ]
