# Generated by Django 5.2.6 on 2026-08-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_corbeilleelement'),
        ('administration', '0004_elementcorbeille_motif'),
    ]

    operations = [
    ]
