# Generated by Django 5.2.6 on 2026-08-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0010_echeancierpaiement_nature_frais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remisereduction',
            name='motif',
            field=models.CharField(choices=[('FRATRIE', 'Réduction fratrie'), ('MERITE', 'Réduction mérite'), ('SOCIALE', 'Réduction sociale'), ('EMPLOYEE', "Enfant d'employé"), ('CLIENT_FIDELE', 'Client fidèle'), ('PROMOTION', 'Promotion'), ('ERREUR_COMMERCIALE', 'Erreur commerciale'), ('PARTENAIRE', 'Partenaire'), ('GESTE_COMMERCIAL', 'Geste commercial'), ('NE_PAIE_RIEN', 'Ne paie rien'), ('MOITIE', 'La moitié'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Motif'),
        ),
    ]
