# Generated by Django 5.2.6 on 2026-09-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0012_isoler_paiements_par_annee'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementremise',
            name='regle_calcul',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
