# Generated by Django 5.2.6 on 2026-08-10 07:48

import ecole_moderne.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0013_paiement_annee_remise_ventilation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echeancierpaiement',
            name='annee_scolaire',
            field=models.CharField(max_length=9, validators=[ecole_moderne.validators.valider_annee_scolaire], verbose_name='Année scolaire'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='annee_scolaire',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Année comptable à laquelle ce paiement doit être affecté.', max_length=9, validators=[ecole_moderne.validators.valider_annee_scolaire], verbose_name='Année scolaire'),
        ),
    ]
