# Generated by Django 5.2.6 on 2026-08-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0012_isoler_paiements_par_annee'),
        ('paiements', '0017_echeanciers_par_annee'),
    ]

    operations = [
    ]
