# Generated by Django 5.2.6 on 2026-08-29 08:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0019_alter_classe_annee_scolaire_and_more'),
        ('paiements', '0018_merge_20260829_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echeancierpaiement',
            name='annee_scolaire',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message="L'année scolaire doit être au format AAAA-AAAA.", regex='^\\d{4}-\\d{4}$')], verbose_name='Année scolaire'),
        ),
        migrations.AlterField(
            model_name='echeancierpaiement',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeanciers', to='eleves.eleve'),
        ),
        migrations.AlterField(
            model_name='echeancierpaiement',
            name='nature_frais',
            field=models.CharField(choices=[('INSCRIPTION', 'Inscription'), ('REINSCRIPTION', 'Réinscription')], db_index=True, default='INSCRIPTION', max_length=20, verbose_name="Nature des frais d'admission"),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='annee_scolaire',
            field=models.CharField(db_index=True, max_length=9, validators=[django.core.validators.RegexValidator(message="L'année scolaire doit être au format AAAA-AAAA.", regex='^\\d{4}-\\d{4}$')], verbose_name='Année scolaire'),
        ),
    ]
