# Generated by Django 5.2.6 on 2026-09-15 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0021_import_verrouille_premier_paiement'),
        ('paiements', '0020_regle_calcul_remises'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='frais_revision_inclus',
            field=models.BooleanField(default=False, help_text='Réduction de 20 000 GNF sur la scolarité, une fois par année. Le versement reste inchangé.', verbose_name='Frais de révision inclus'),
        ),
        migrations.AddField(
            model_name='paiementremise',
            name='origine_revision',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddConstraint(
            model_name='paiement',
            constraint=models.UniqueConstraint(condition=models.Q(('frais_revision_inclus', True), ('statut__in', ['EN_ATTENTE', 'VALIDE'])), fields=('eleve', 'annee_scolaire'), name='revision_unique_eleve_annee_active'),
        ),
        migrations.AddConstraint(
            model_name='paiementremise',
            constraint=models.UniqueConstraint(condition=models.Q(('origine_revision', True)), fields=('paiement',), name='revision_unique_lien_paiement'),
        ),
    ]
