# Generated by Django 5.2.6 on 2026-09-08 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        ('eleves', '0020_import_verrouille_premier_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='recherchepopulaire',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eleves.ecole'),
        ),
    ]
