# Generated by Django 5.2.7 on 2025-11-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0009_profil_peut_supprimer_enseignants_definitivement'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='peut_importer_eleves',
            field=models.BooleanField(default=False, verbose_name='Peut importer des élèves'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='peut_gerer_notes',
            field=models.BooleanField(default=True, verbose_name='Peut gérer les notes et matières (DÉSACTIVÉ)'),
        ),
    ]
