# Generated by Django 5.2.7 on 2026-01-21 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0010_rendre_champs_optionnels'),
        ('utilisateurs', '0010_merge_20251107_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profils', to='eleves.ecole', verbose_name='École'),
        ),
    ]
