# Generated by Django 5.2.6 on 2026-08-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0014_profil_lecture_seule'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='peut_supprimer_eleves',
            field=models.BooleanField(default=True, help_text="L'élève supprimé part dans la corbeille et reste restaurable.", verbose_name='Peut supprimer les élèves (vers la corbeille)'),
        ),
    ]
