# Generated by Django 5.2.6 on 2026-08-18 12:25

import django.db.models.deletion
from django.db import migrations, models


def identifier_comptes_principaux_existants(apps, schema_editor):
    Profil = apps.get_model('utilisateurs', 'Profil')
    Ecole = apps.get_model('eleves', 'Ecole')
    menus = ['eleves', 'paiements', 'depenses', 'salaires', 'bus', 'notes', 'rapports']

    for ecole in Ecole.objects.all().iterator():
        candidat = None
        if ecole.created_by_id:
            candidat = (
                Profil.objects
                .filter(
                    user_id=ecole.created_by_id,
                    user__is_superuser=False,
                    est_compte_principal=False,
                )
                .filter(models.Q(ecole_id=ecole.id) | models.Q(ecole_id__isnull=True))
                .first()
            )
        if candidat is None:
            candidat = (
                Profil.objects
                .filter(
                    ecole_id=ecole.id,
                    role__in=['DIRECTEUR', 'ADMIN'],
                    user__is_superuser=False,
                    est_compte_principal=False,
                )
                .order_by('id')
                .first()
            )
        if candidat is None:
            continue

        candidat.ecole_id = ecole.id
        candidat.role = 'DIRECTEUR'
        candidat.est_compte_principal = True
        candidat.compte_principal_id = None
        candidat.peut_gerer_utilisateurs = True
        candidat.peut_gerer_classes = True
        candidat.peut_gerer_grilles_tarifaires = True
        candidat.allowed_menus = menus
        candidat.is_validated = True
        candidat.actif = True
        candidat.save()

        # Les anciens comptes de l'école deviennent des sous-utilisateurs du
        # principal. Une liste vide de menus signifiait auparavant « sans
        # restriction » : on la convertit explicitement pour éviter de les bloquer.
        for sous_profil in (
            Profil.objects
            .filter(ecole_id=ecole.id, user__is_superuser=False)
            .exclude(pk=candidat.pk)
            .iterator()
        ):
            sous_profil.est_compte_principal = False
            sous_profil.compte_principal_id = candidat.pk
            sous_profil.peut_gerer_utilisateurs = False
            if not sous_profil.allowed_menus:
                sous_profil.allowed_menus = menus
            sous_profil.save()


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0014_profil_lecture_seule'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='compte_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_utilisateurs', to='utilisateurs.profil', verbose_name='Compte principal responsable'),
        ),
        migrations.AddField(
            model_name='profil',
            name='est_compte_principal',
            field=models.BooleanField(default=False, help_text='Le compte principal peut gérer la structure et les sous-utilisateurs de son école.', verbose_name="Compte principal de l'école"),
        ),
        migrations.AddField(
            model_name='profil',
            name='peut_gerer_classes',
            field=models.BooleanField(default=False, verbose_name='Peut créer et modifier les classes'),
        ),
        migrations.AddField(
            model_name='profil',
            name='peut_gerer_grilles_tarifaires',
            field=models.BooleanField(default=False, verbose_name='Peut gérer les grilles tarifaires'),
        ),
        migrations.RunPython(identifier_comptes_principaux_existants, migrations.RunPython.noop),
    ]
