# Generated by Django 5.2.6 on 2026-08-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0015_profil_peut_supprimer_eleves'),
        ('utilisateurs', '0016_reparer_comptes_principaux_ecoles'),
    ]

    operations = [
    ]
