# Generated by Django 5.2.7 on 2025-10-30 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0009_alter_eleve_date_naissance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la classe')),
                ('niveau', models.CharField(choices=[('GARDERIE', 'Garderie'), ('MATERNELLE', 'Maternelle'), ('PRIMAIRE_1', 'Primaire 1ère'), ('PRIMAIRE_2', 'Primaire 2ème'), ('PRIMAIRE_3', 'Primaire 3ème'), ('PRIMAIRE_4', 'Primaire 4ème'), ('PRIMAIRE_5', 'Primaire 5ème'), ('PRIMAIRE_6', 'Primaire 6ème'), ('COLLEGE_7', 'Collège 7ème'), ('COLLEGE_8', 'Collège 8ème'), ('COLLEGE_9', 'Collège 9ème'), ('COLLEGE_10', 'Collège 10ème'), ('LYCEE_11', 'Lycée 11ème'), ('LYCEE_12', 'Lycée 12ème'), ('TERMINALE', 'Terminale')], max_length=20, verbose_name='Niveau')),
                ('annee_scolaire', models.CharField(help_text='Format: 2024-2025', max_length=9, verbose_name='Année scolaire')),
                ('effectif', models.PositiveIntegerField(default=0, verbose_name='Effectif')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_notes_creees', to=settings.AUTH_USER_MODEL)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_notes', to='eleves.ecole')),
            ],
            options={
                'verbose_name': 'Classe (Notes)',
                'verbose_name_plural': 'Classes (Notes)',
                'ordering': ['niveau', 'nom'],
                'unique_together': {('ecole', 'nom', 'annee_scolaire')},
            },
        ),
    ]
