# Generated by Django 5.2.7 on 2025-10-31 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0009_alter_eleve_date_naissance'),
        ('notes', '0002_matierenote_evaluation_noteeleve'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('SEMESTRE_1', 'Semestre 1'), ('SEMESTRE_2', 'Semestre 2'), ('TRIMESTRE_1', 'Trimestre 1'), ('TRIMESTRE_2', 'Trimestre 2'), ('TRIMESTRE_3', 'Trimestre 3')], max_length=20, verbose_name='Période')),
                ('annee_scolaire', models.CharField(max_length=9, verbose_name='Année scolaire')),
                ('note', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Note sur 20')),
                ('absent', models.BooleanField(default=False, verbose_name='Absent')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='eleves.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='notes.matierenote')),
            ],
            options={
                'verbose_name': 'Note de composition',
                'verbose_name_plural': 'Notes de composition',
                'ordering': ['eleve', 'matiere', 'periode'],
                'unique_together': {('eleve', 'matiere', 'periode', 'annee_scolaire')},
            },
        ),
        migrations.CreateModel(
            name='NoteMensuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(choices=[('OCTOBRE', 'Octobre'), ('NOVEMBRE', 'Novembre'), ('DECEMBRE', 'Décembre'), ('JANVIER', 'Janvier'), ('FEVRIER', 'Février'), ('MARS', 'Mars'), ('AVRIL', 'Avril'), ('MAI', 'Mai')], max_length=20, verbose_name='Mois')),
                ('annee_scolaire', models.CharField(max_length=9, verbose_name='Année scolaire')),
                ('note', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Note sur 20')),
                ('absent', models.BooleanField(default=False, verbose_name='Absent')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_mensuelles', to='eleves.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_mensuelles', to='notes.matierenote')),
            ],
            options={
                'verbose_name': 'Note mensuelle',
                'verbose_name_plural': 'Notes mensuelles',
                'ordering': ['eleve', 'matiere', 'mois'],
                'unique_together': {('eleve', 'matiere', 'mois', 'annee_scolaire')},
            },
        ),
    ]
