# Generated by Django 5.2.7 on 2025-10-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_compositionnote_notemensuelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='classenote',
            name='niveau_enseignement',
            field=models.CharField(choices=[('PRIMAIRE', 'Primaire'), ('SECONDAIRE', 'Secondaire')], default='SECONDAIRE', max_length=20, verbose_name="Niveau d'enseignement"),
        ),
    ]
