# Generated by Django 5.2.7 on 2025-10-31 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0009_alter_eleve_date_naissance'),
        ('notes', '0004_classenote_niveau_enseignement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='classenote',
            name='niveau_enseignement',
            field=models.CharField(choices=[('MATERNELLE', 'Maternelle'), ('PRIMAIRE', 'Primaire'), ('SECONDAIRE', 'Secondaire')], default='SECONDAIRE', max_length=20, verbose_name="Niveau d'enseignement"),
        ),
        migrations.CreateModel(
            name='AppreciationMaternelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(choices=[('TRIMESTRE_1', 'Trimestre 1'), ('TRIMESTRE_2', 'Trimestre 2'), ('TRIMESTRE_3', 'Trimestre 3')], max_length=20, verbose_name='Trimestre')),
                ('annee_scolaire', models.CharField(max_length=9, verbose_name='Année scolaire')),
                ('appreciation', models.CharField(choices=[('TRES_BIEN_ACQUIS', 'Très Bien Acquis'), ('BIEN_ACQUIS', 'Bien Acquis'), ('EN_COURS', "En Cours d'Acquisition"), ('NON_ACQUIS', 'Non Acquis')], max_length=20, verbose_name='Appréciation')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('absent', models.BooleanField(default=False, verbose_name='Absent')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciations_maternelle', to='eleves.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciations_maternelle', to='notes.matierenote')),
            ],
            options={
                'verbose_name': 'Appréciation maternelle',
                'verbose_name_plural': 'Appréciations maternelle',
                'ordering': ['eleve', 'matiere', 'trimestre'],
                'unique_together': {('eleve', 'matiere', 'trimestre', 'annee_scolaire')},
            },
        ),
    ]
