# Generated by Django 5.2.7 on 2025-11-01 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0009_alter_eleve_date_naissance'),
        ('notes', '0005_alter_classenote_niveau_enseignement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du thème')),
                ('couleur_primaire', models.CharField(default='#2c3e50', help_text='Ex: #2c3e50', max_length=7, verbose_name='Couleur primaire')),
                ('couleur_secondaire', models.CharField(default='#3498db', help_text='Ex: #3498db', max_length=7, verbose_name='Couleur secondaire')),
                ('couleur_accent', models.CharField(default='#e74c3c', help_text='Ex: #e74c3c', max_length=7, verbose_name='Couleur accent')),
                ('couleur_texte_principal', models.CharField(default='#2c3e50', max_length=7, verbose_name='Texte principal')),
                ('couleur_texte_secondaire', models.CharField(default='#7f8c8d', max_length=7, verbose_name='Texte secondaire')),
                ('couleur_fond_header', models.CharField(default='#2c3e50', max_length=7, verbose_name='Fond en-tête')),
                ('couleur_fond_tableau', models.CharField(default='#ecf0f1', max_length=7, verbose_name='Fond tableau')),
                ('couleur_fond_carte', models.CharField(default='#ffffff', max_length=7, verbose_name='Fond cartes')),
                ('couleur_bordure', models.CharField(default='#bdc3c7', max_length=7, verbose_name='Bordures')),
                ('couleur_mention_tb', models.CharField(default='#27ae60', max_length=7, verbose_name='Mention Très Bien')),
                ('couleur_mention_bien', models.CharField(default='#3498db', max_length=7, verbose_name='Mention Bien')),
                ('couleur_mention_ab', models.CharField(default='#f39c12', max_length=7, verbose_name='Mention Assez Bien')),
                ('couleur_mention_passable', models.CharField(default='#e67e22', max_length=7, verbose_name='Mention Passable')),
                ('couleur_mention_insuffisant', models.CharField(default='#e74c3c', max_length=7, verbose_name='Mention Insuffisant')),
                ('actif', models.BooleanField(default=False, verbose_name='Thème actif')),
                ('par_defaut', models.BooleanField(default=False, verbose_name='Thème par défaut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes_bulletin', to='eleves.ecole')),
            ],
            options={
                'verbose_name': 'Thème de bulletin',
                'verbose_name_plural': 'Thèmes de bulletin',
                'ordering': ['-par_defaut', '-actif', 'nom'],
            },
        ),
    ]
