# Generated by Django 5.2.7 on 2025-11-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_themebulletin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='periode',
            field=models.CharField(choices=[('OCTOBRE', 'Octobre'), ('NOVEMBRE', 'Novembre'), ('DECEMBRE', 'Décembre'), ('JANVIER', 'Janvier'), ('FEVRIER', 'Février'), ('MARS', 'Mars'), ('AVRIL', 'Avril'), ('MAI', 'Mai'), ('JUIN', 'Juin'), ('TRIMESTRE_1', 'Trimestre 1'), ('TRIMESTRE_2', 'Trimestre 2'), ('TRIMESTRE_3', 'Trimestre 3'), ('SEMESTRE_1', 'Semestre 1'), ('SEMESTRE_2', 'Semestre 2')], max_length=20, verbose_name='Période'),
        ),
    ]
