# Generated by Django 5.2.7 on 2025-11-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_ajouter_periodes_mensuelles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteeleve',
            name='note',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Note obtenue'),
        ),
    ]
