# Generated by Django 5.2.7 on 2025-11-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_noteeleve_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matierenote',
            name='coefficient',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=4, null=True, verbose_name='Coefficient'),
        ),
    ]
