# Generated by Django 5.2.7 on 2025-11-21 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0009_alter_eleve_date_naissance'),
        ('notes', '0009_alter_matierenote_coefficient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=50, verbose_name='Période')),
                ('annee_scolaire', models.CharField(max_length=9, verbose_name='Année scolaire')),
                ('moyenne_generale', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Moyenne générale')),
                ('total_points', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total points')),
                ('total_coefficients', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total coefficients')),
                ('rang', models.PositiveIntegerField(verbose_name='Rang')),
                ('rang_formate', models.CharField(max_length=20, verbose_name='Rang formaté')),
                ('effectif', models.PositiveIntegerField(verbose_name='Effectif de la classe')),
                ('mention', models.CharField(blank=True, max_length=50, verbose_name='Mention')),
                ('appreciation', models.TextField(blank=True, verbose_name='Appréciation')),
                ('date_calcul', models.DateTimeField(auto_now=True, verbose_name='Date du calcul')),
                ('calcule_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classements', to='notes.classenote')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classements', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Classement',
                'verbose_name_plural': 'Classements',
                'ordering': ['classe', 'periode', 'rang'],
                'indexes': [models.Index(fields=['classe', 'periode', 'annee_scolaire'], name='notes_class_classe__52dfff_idx'), models.Index(fields=['eleve', 'periode'], name='notes_class_eleve_i_4bea5e_idx')],
                'unique_together': {('eleve', 'classe', 'periode', 'annee_scolaire')},
            },
        ),
    ]
