# Generated by Django 5.2.7 on 2025-12-09 22:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0009_alter_eleve_date_naissance'),
        ('notes', '0010_classement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='compositionnote',
            index=models.Index(fields=['annee_scolaire', 'periode'], name='notes_compo_annee_s_3a0c82_idx'),
        ),
        migrations.AddIndex(
            model_name='compositionnote',
            index=models.Index(fields=['eleve', 'annee_scolaire'], name='notes_compo_eleve_i_692c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='compositionnote',
            index=models.Index(fields=['matiere', 'annee_scolaire'], name='notes_compo_matiere_d81fea_idx'),
        ),
        migrations.AddIndex(
            model_name='notemensuelle',
            index=models.Index(fields=['annee_scolaire', 'mois'], name='notes_notem_annee_s_179f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='notemensuelle',
            index=models.Index(fields=['eleve', 'annee_scolaire'], name='notes_notem_eleve_i_9d3c09_idx'),
        ),
        migrations.AddIndex(
            model_name='notemensuelle',
            index=models.Index(fields=['matiere', 'annee_scolaire'], name='notes_notem_matiere_cce9c2_idx'),
        ),
    ]
