# Generated by Django 5.2.7 on 2026-01-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_optimisation_index'),
        ('notes', '0012_bulletinmaternelle'),
    ]

    operations = [
    ]
