# Generated by Django 5.2.6 on 2026-09-05 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0019_ecole_couleurs_cartes'),
        ('notes', '0013_creneauemploidutemps'),
        ('salaires', '0009_enseignant_fonction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesEnseignantTemporaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empreinte_lien', models.CharField(editable=False, max_length=64, unique=True)),
                ('expire_le', models.DateTimeField()),
                ('revoque_le', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('classes', models.ManyToManyField(related_name='acces_enseignants', to='notes.classenote')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations_notes_creees', to=settings.AUTH_USER_MODEL)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_notes_enseignants', to='eleves.ecole')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acces_notes', to='salaires.enseignant')),
                ('matieres', models.ManyToManyField(related_name='acces_enseignants', to='notes.matierenote')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='acces_notes_temporaire', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accès temporaire enseignant',
                'verbose_name_plural': 'Accès temporaires enseignants',
                'ordering': ['-cree_le'],
            },
        ),
    ]
