# Generated by Django 5.2.7 on 2026-01-21 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0010_rendre_champs_optionnels'),
        ('notes', '0013_merge_0011_optimisation_index_0012_bulletinmaternelle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulletinmaternelle',
            options={'ordering': ['eleve', 'trimestre'], 'verbose_name': 'Bulletin maternelle', 'verbose_name_plural': 'Bulletins maternelle'},
        ),
        migrations.AlterUniqueTogether(
            name='bulletinmaternelle',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bulletinmaternelle',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bulletinmaternelle',
            name='signature_directeur',
            field=models.BooleanField(default=False, verbose_name='Signé par le directeur'),
        ),
        migrations.AddField(
            model_name='bulletinmaternelle',
            name='signature_monitrice',
            field=models.BooleanField(default=False, verbose_name='Signé par la monitrice'),
        ),
        migrations.AlterField(
            model_name='appreciationmaternelle',
            name='appreciation',
            field=models.CharField(choices=[('A+', 'Excellent'), ('A', 'Très bien'), ('B+', 'Bien'), ('B', 'Assez bien'), ('B-', 'Moyen'), ('C', 'Passable'), ('D', 'Éprouve des difficultés')], max_length=20, verbose_name='Appréciation'),
        ),
        migrations.AlterField(
            model_name='bulletinmaternelle',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins_maternelle', to='notes.classenote'),
        ),
        migrations.AlterField(
            model_name='bulletinmaternelle',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins_maternelle', to='eleves.eleve'),
        ),
        migrations.AlterField(
            model_name='bulletinmaternelle',
            name='trimestre',
            field=models.CharField(choices=[('TRIMESTRE_1', 'Trimestre 1'), ('TRIMESTRE_2', 'Trimestre 2'), ('TRIMESTRE_3', 'Trimestre 3')], max_length=20, verbose_name='Trimestre'),
        ),
        migrations.AlterUniqueTogether(
            name='bulletinmaternelle',
            unique_together={('eleve', 'trimestre', 'annee_scolaire')},
        ),
        migrations.CreateModel(
            name='EvaluationMaternelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(choices=[('TRIMESTRE_1', 'Trimestre 1'), ('TRIMESTRE_2', 'Trimestre 2'), ('TRIMESTRE_3', 'Trimestre 3')], max_length=20, verbose_name='Trimestre')),
                ('annee_scolaire', models.CharField(max_length=9, verbose_name='Année scolaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_maternelle', to='notes.classenote')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_maternelle_creees', to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_maternelle', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Évaluation maternelle',
                'verbose_name_plural': 'Évaluations maternelle',
                'ordering': ['eleve', 'trimestre'],
                'unique_together': {('eleve', 'classe', 'trimestre', 'annee_scolaire')},
            },
        ),
        migrations.CreateModel(
            name='AnalyseTravailMaternelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprend_demandes', models.BooleanField(default=False, verbose_name="L'enfant comprend ce qu'on lui demande")),
                ('ne_comprend_pas', models.BooleanField(default=False, verbose_name="L'enfant ne comprend pas ce qu'on lui demande")),
                ('trop_jeune', models.BooleanField(default=False, verbose_name="L'enfant est trop jeune pour cette classe")),
                ('fixe_attention', models.BooleanField(default=False, verbose_name="L'enfant fixe son attention")),
                ('pas_probleme_monitrice', models.BooleanField(default=False, verbose_name="L'enfant n'a pas de problème avec sa monitrice")),
                ('pas_probleme_camarades', models.BooleanField(default=False, verbose_name="L'enfant n'a pas de problème avec ses camarades")),
                ('pas_probleme_famille', models.BooleanField(default=False, verbose_name="L'enfant n'a pas de problème avec sa famille")),
                ('est_doue', models.BooleanField(default=False, verbose_name="L'enfant est doué")),
                ('est_paresseux', models.BooleanField(default=False, verbose_name="L'enfant est paresseux")),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire supplémentaire')),
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyse_travail', to='notes.evaluationmaternelle')),
            ],
            options={
                'verbose_name': 'Analyse du travail (maternelle)',
                'verbose_name_plural': 'Analyses du travail (maternelle)',
            },
        ),
        migrations.CreateModel(
            name='RecommandationMaternelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encourager_feliciter', models.BooleanField(default=False, verbose_name='Enfant à encourager et à féliciter')),
                ('suivre_domicile', models.BooleanField(default=False, verbose_name='Enfant à suivre à domicile')),
                ('gouter_dans_sac', models.BooleanField(default=False, verbose_name="Mettre le goûter dans le sac de l'enfant")),
                ('aide_encouragement_parents', models.BooleanField(default=False, verbose_name="L'enfant a besoin d'aide et d'encouragement des parents")),
                ('amour_parental', models.BooleanField(default=False, verbose_name="L'enfant a besoin de l'amour maternel et paternel")),
                ('besoin_epanouissement', models.BooleanField(default=False, verbose_name="L'enfant a besoin d'être épanoui")),
                ('sorties_educatives', models.BooleanField(default=False, verbose_name="L'enfant a besoin de sorties éducatives et récréatives")),
                ('aide_intellectuelle', models.BooleanField(default=False, verbose_name="L'enfant a besoin de l'aide de la monitrice et des parents pour développer ses facultés intellectuelles")),
                ('douceur_patience', models.BooleanField(default=False, verbose_name="L'enfant doit être pris avec beaucoup de douceur et de patience")),
                ('besoin_fermete', models.BooleanField(default=False, verbose_name="L'enfant a besoin de fermeté")),
                ('esprit_inferiorite', models.BooleanField(default=False, verbose_name="L'enfant a un esprit d'infériorité")),
                ('attention_particuliere', models.BooleanField(default=False, verbose_name="L'enfant a besoin d'une attention particulière des parents")),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Recommandation personnalisée')),
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='notes.evaluationmaternelle')),
            ],
            options={
                'verbose_name': 'Recommandation (maternelle)',
                'verbose_name_plural': 'Recommandations (maternelle)',
            },
        ),
        migrations.CreateModel(
            name='NoteMaternelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Note sur 10')),
                ('lettre', models.CharField(blank=True, max_length=2, verbose_name='Lettre')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_matieres', to='notes.evaluationmaternelle')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_maternelle', to='notes.matierenote')),
            ],
            options={
                'verbose_name': 'Note maternelle',
                'verbose_name_plural': 'Notes maternelle',
                'unique_together': {('evaluation', 'matiere')},
            },
        ),
    ]
