# Generated by Django 5.2.7 on 2026-01-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_alter_bulletinmaternelle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemensuelle',
            name='mois',
            field=models.CharField(choices=[('OCTOBRE', 'Octobre'), ('NOVEMBRE', 'Novembre'), ('DECEMBRE', 'Décembre'), ('JANVIER', 'Janvier'), ('FEVRIER', 'Février'), ('MARS', 'Mars'), ('AVRIL', 'Avril'), ('MAI', 'Mai'), ('JUIN', 'Juin')], max_length=20, verbose_name='Mois'),
        ),
        migrations.AlterField(
            model_name='notemensuelle',
            name='note',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Note sur 20'),
        ),
    ]
