# Generated by Django 5.2.17 on 2026-09-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_acces_enseignants_temporaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesenseignanttemporaire',
            name='type_acces',
            field=models.CharField(choices=[('NOTES', 'Notes (dont bonus de participation)'), ('PRESENCE', 'Présence (appel)')], default='NOTES', max_length=10),
        ),
    ]
