# Generated by Django 5.2.6 on 2026-09-08 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0020_import_verrouille_premier_paiement'),
        ('synchronisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField(unique=True)),
                ('snapshot_cursor', models.TextField(blank=True)),
                ('initial_complete', models.BooleanField(default=False)),
                ('last_change_id', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SyncOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=120)),
                ('object_uuid', models.UUIDField()),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.ecole')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('model_label', 'object_uuid'), name='sync_object_school_unique')],
            },
        ),
    ]
