# Generated by Django 5.2.6 on 2026-08-30 14:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0012_isoler_paiements_par_annee'),
        ('salaires', '0006_modes_calcul_heures'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='etatsalaire',
            name='avances',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total des avances de salaire rattachées à cette période', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Avances déjà versées'),
        ),
        migrations.CreateModel(
            name='AvanceSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
                ('sync_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name="Montant de l'avance (GNF)")),
                ('date_avance', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Date de versement')),
                ('reference_externe', models.CharField(blank=True, help_text='Numéro de reçu, transaction Mobile Money, chèque, etc.', max_length=100, verbose_name='Référence externe')),
                ('motif', models.TextField(blank=True, verbose_name='Motif / observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avances_salaire_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances_salaire', to='salaires.enseignant', verbose_name='Enseignant')),
                ('mode_paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avances_salaire', to='paiements.modepaiement', verbose_name='Mode de paiement')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avances_salaire', to='salaires.periodesalaire', verbose_name='Période de retenue')),
            ],
            options={
                'verbose_name': 'Avance de salaire',
                'verbose_name_plural': 'Avances de salaire',
                'ordering': ['-date_avance', '-date_creation'],
                'indexes': [models.Index(fields=['enseignant', 'periode'], name='salaires_av_enseign_9d04ee_idx'), models.Index(fields=['date_avance'], name='salaires_av_date_av_8d4cec_idx')],
            },
        ),
    ]
