# Generated by Django 5.2.6 on 2026-08-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0006_etatsalaire_heures_mensuelles_saisies'),
        ('salaires', '0006_modes_calcul_heures'),
    ]

    operations = [
    ]
