# Generated by Django 5.2.6 on 2026-08-29 08:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0007_merge_20260829_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etatsalaire',
            name='heures_mensuelles_saisies',
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='type_enseignant',
            field=models.CharField(choices=[('GARDERIE', 'Garderie'), ('MATERNELLE', 'Maternelle'), ('PRIMAIRE', 'Primaire'), ('SECONDAIRE', 'Secondaire (taux horaire)'), ('ADMINISTRATEUR', 'Administrateur')], max_length=20, verbose_name="Type d'enseignant"),
        ),
        migrations.AlterField(
            model_name='etatsalaire',
            name='taux_horaire_applique',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Taux conservé au moment du calcul pour l'historique", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Taux horaire appliqué'),
        ),
    ]
