# Generated by Django 5.2.6 on 2026-08-30 16:48

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0008_remove_etatsalaire_heures_mensuelles_saisies_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='etatsalaire',
            name='avances_deduites',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Montant des avances récupéré sur ce salaire', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Avances déduites'),
        ),
        migrations.CreateModel(
            name='AvanceSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
                ('sync_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('date_avance', models.DateField(default=datetime.datetime.now, verbose_name="Date de l'avance")),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name="Montant de l'avance (GNF)")),
                ('motif', models.TextField(verbose_name='Motif')),
                ('reference_externe', models.CharField(blank=True, max_length=100, verbose_name='Référence externe / numéro de reçu')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avances_salaire_creees', to=settings.AUTH_USER_MODEL)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avances_salaire', to='salaires.enseignant', verbose_name='Enseignant')),
                ('periode_prevue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avances_salaire', to='salaires.periodesalaire', verbose_name='Première période de retenue')),
            ],
            options={
                'verbose_name': 'Avance sur salaire',
                'verbose_name_plural': 'Avances sur salaire',
                'ordering': ['-date_avance', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RemboursementAvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
                ('sync_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant remboursé')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('avance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='salaires.avancesalaire', verbose_name='Avance')),
                ('etat_salaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements_avances', to='salaires.etatsalaire', verbose_name='État de salaire')),
            ],
            options={
                'verbose_name': "Remboursement d'avance",
                'verbose_name_plural': "Remboursements d'avances",
                'ordering': ['etat_salaire__periode__annee', 'etat_salaire__periode__mois', 'id'],
                'constraints': [models.UniqueConstraint(fields=('avance', 'etat_salaire'), name='unique_avance_par_etat_salaire')],
            },
        ),
    ]
