# Generated by Django 5.2.6 on 2026-09-05 21:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0009_enseignant_fonction'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='prime_mensuelle',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Reprise dans chaque nouvel état de salaire. Les états déjà créés gardent leur prime, ajustable séparément avant validation.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime mensuelle par défaut (GNF)'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='salaire_fixe',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pour le personnel à salaire fixe (hors secondaire)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Salaire fixe (GNF)'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='type_enseignant',
            field=models.CharField(choices=[('GARDERIE', 'Garderie'), ('MATERNELLE', 'Maternelle'), ('PRIMAIRE', 'Primaire'), ('SECONDAIRE', 'Secondaire (taux horaire)'), ('ADMINISTRATEUR', 'Administrateur'), ('CHAUFFEUR', 'Chauffeur'), ('VIGILE', 'Vigiles'), ('ENTRETIEN', 'Service entretien'), ('NOUNOU', 'Nounou'), ('RESTAURATION', 'Restauration')], max_length=20, verbose_name="Type d'enseignant"),
        ),
    ]
