# Generated by Django 5.2.17 on 2026-09-22 19:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models
from django.db.models import F


def reprendre_primes_existantes(apps, schema_editor):
    """Les primes déjà saisies deviennent la prime de fonction.

    Le total ``primes`` est désormais la somme des six colonnes ; sans cette
    reprise, le prochain enregistrement d'un ancien état effacerait sa prime.
    """
    EtatSalaire = apps.get_model('salaires', 'EtatSalaire')
    EtatSalaire.objects.filter(primes__gt=0).update(prime_fonction=F('primes'))

    from salaires.models import jours_ouvrables_du_mois

    PeriodeSalaire = apps.get_model('salaires', 'PeriodeSalaire')
    for periode in PeriodeSalaire.objects.filter(jours_ouvrables__isnull=True):
        PeriodeSalaire.objects.filter(pk=periode.pk).update(
            jours_ouvrables=jours_ouvrables_du_mois(periode.annee, periode.mois)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0010_personnel_et_prime_mensuelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text="Sert au calcul de la prime d'éloignement (km × taux de la période).", max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Distance domicile - école (km)'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='matricule',
            field=models.CharField(blank=True, help_text='Matricule du travailleur repris sur les états et le bulletin de paie.', max_length=30, verbose_name='Matricule'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='effectif_classe',
            field=models.PositiveIntegerField(default=0, help_text='Élèves de la classe au moment du calcul (prime de craie).', verbose_name='Effectif de la classe'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='heures_revision',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Heures de révision'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='jours_chomes',
            field=models.PositiveSmallIntegerField(default=0, help_text='Retirés du nombre de jours de travail de la période.', validators=[django.core.validators.MaxValueValidator(31)], verbose_name='Jours chômés'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='prime_anciennete',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Prime d'ancienneté"),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='prime_craie',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime de craie / révision'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='prime_eloignement',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Prime d'éloignement"),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='prime_exceptionnelle',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime exceptionnelle'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='prime_fonction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime de fonction'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='prime_performance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime de performance'),
        ),
        migrations.AddField(
            model_name='periodesalaire',
            name='jours_ouvrables',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Jours travaillés du mois. Rempli automatiquement avec les jours du lundi au vendredi ; retirez les jours fériés si besoin.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Nombre de jours de travail'),
        ),
        migrations.AddField(
            model_name='periodesalaire',
            name='lieu_edition',
            field=models.CharField(blank=True, help_text='Ex. : Diécké. Utilisé dans « Diécké, le 31 mai 2026 ».', max_length=100, verbose_name="Lieu d'édition"),
        ),
        migrations.AddField(
            model_name='periodesalaire',
            name='signataires',
            field=models.TextField(blank=True, help_text='Un signataire par ligne, au format « Titre : Nom ». Ex. : Le Fondateur : M. Nyan Isaac NIAMY', verbose_name='Signataires'),
        ),
        migrations.AddField(
            model_name='periodesalaire',
            name='taux_heure_revision',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Secondaire : heures de révision × ce montant.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Heure de révision (GNF)'),
        ),
        migrations.AddField(
            model_name='periodesalaire',
            name='taux_prime_anciennete',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Prime d'ancienneté par année (GNF)"),
        ),
        migrations.AddField(
            model_name='periodesalaire',
            name='taux_prime_craie',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Maternelle et primaire : effectif de la classe × ce montant.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime de craie par élève (GNF)'),
        ),
        migrations.AddField(
            model_name='periodesalaire',
            name='taux_prime_eloignement',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Prime d'éloignement par km (GNF)"),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='prime_mensuelle',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Reprise dans chaque nouvel état de salaire. Les états déjà créés gardent leur prime, ajustable séparément avant validation.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime de fonction mensuelle (GNF)'),
        ),
        migrations.AlterField(
            model_name='etatsalaire',
            name='primes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Total des six primes détaillées, recalculé à l'enregistrement.", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Primes'),
        ),
        migrations.RunPython(reprendre_primes_existantes, migrations.RunPython.noop),
    ]
