# Generated by Django 5.2.6 on 2026-09-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0011_enseignant_classe_principale_fonction'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='photo',
            field=models.ImageField(blank=True, upload_to='enseignants/photos/%Y/%m/', verbose_name='Photo'),
        ),
    ]
