# Generated by Django 5.2.6 on 2026-09-24 21:31

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


def reporter_primes_existantes(apps, schema_editor):
    """Les anciens états n'avaient qu'un total de primes : il devient une
    prime exceptionnelle figée pour que les montants restent identiques."""
    EtatSalaire = apps.get_model('salaires', 'EtatSalaire')
    for etat in EtatSalaire.objects.filter(primes__gt=0).only('id', 'primes'):
        EtatSalaire.objects.filter(pk=etat.pk).update(
            prime_exceptionnelle=etat.primes,
            primes_ajustees=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0021_import_verrouille_premier_paiement'),
        ('salaires', '0012_enseignant_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Sert au calcul de la prime d'éloignement.", max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Distance domicile-école (km)'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='matricule',
            field=models.CharField(blank=True, max_length=30, verbose_name='Matricule'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='prime_exceptionnelle',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime exceptionnelle (GNF)'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='prime_fonction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Montant mensuel fixe reporté sur chaque état de salaire.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime de fonction (GNF)'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='prime_performance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime de performance (GNF)'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='professeur_principal',
            field=models.BooleanField(default=False, help_text='Secondaire : ouvre droit à la prime de professeur principal.', verbose_name='Professeur principal'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='effectif_classe',
            field=models.PositiveIntegerField(default=0, help_text='Effectif retenu pour la prime de craie au moment du calcul.', verbose_name='Effectif de la classe'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='heures_revision',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Heures de révision'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='prime_anciennete',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Prime d'ancienneté"),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='prime_craie',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime de craie / révision'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='prime_eloignement',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Prime d'éloignement"),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='prime_exceptionnelle',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime exceptionnelle'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='prime_fonction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime de fonction'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='prime_performance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime de performance'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='primes_ajustees',
            field=models.BooleanField(default=False, help_text='Si coché, un recalcul conserve les primes saisies sur cet état.', verbose_name='Primes saisies manuellement'),
        ),
        migrations.AlterField(
            model_name='etatsalaire',
            name='primes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total des rubriques de primes, recalculé à chaque enregistrement.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Primes'),
        ),
        migrations.CreateModel(
            name='ParametrePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
                ('sync_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('jours_ouvrables', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Jours ouvrables par mois')),
                ('taux_anciennete_par_an', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Ex. 10 000 GNF par année d'ancienneté.", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Prime d'ancienneté par année (GNF)")),
                ('taux_eloignement_par_km', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Ex. 2 000 GNF par km.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Prime d'éloignement par km (GNF)")),
                ('prime_craie_par_eleve', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Garderie, maternelle et primaire : effectif de la classe principale × ce montant (ex. 500 GNF).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime de craie par élève de la classe (GNF)')),
                ('prime_par_heure_revision', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Ex. 10 000 GNF par heure.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime par heure de révision (GNF)')),
                ('prime_professeur_principal', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Ex. 50 000 GNF par mois.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime de professeur principal (GNF)')),
                ('signataire_1_titre', models.CharField(blank=True, default='La Fondation', max_length=80, verbose_name='Signataire 1 - titre')),
                ('signataire_1_nom', models.CharField(blank=True, max_length=120, verbose_name='Signataire 1 - nom')),
                ('signataire_2_titre', models.CharField(blank=True, default='Le Directeur Général', max_length=80, verbose_name='Signataire 2 - titre')),
                ('signataire_2_nom', models.CharField(blank=True, max_length=120, verbose_name='Signataire 2 - nom')),
                ('signataire_3_titre', models.CharField(blank=True, default='La Gestionnaire', max_length=80, verbose_name='Signataire 3 - titre')),
                ('signataire_3_nom', models.CharField(blank=True, max_length=120, verbose_name='Signataire 3 - nom')),
                ('lieu_signature', models.CharField(blank=True, max_length=80, verbose_name='Lieu de signature')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ecole', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametre_paie', to='eleves.ecole', verbose_name='École')),
            ],
            options={
                'verbose_name': 'Paramètres de paie',
                'verbose_name_plural': 'Paramètres de paie',
            },
        ),
        migrations.RunPython(reporter_primes_existantes, migrations.RunPython.noop),
    ]
