# Generated by Django 5.2.6 on 2026-09-25 05:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0013_primes_detaillees_parametres_paie'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='heures_jeudi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('24'))], verbose_name='Heures du jeudi'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='heures_lundi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('24'))], verbose_name='Heures du lundi'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='heures_mardi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('24'))], verbose_name='Heures du mardi'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='heures_mercredi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('24'))], verbose_name='Heures du mercredi'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='heures_samedi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('24'))], verbose_name='Heures du samedi'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='heures_vendredi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('24'))], verbose_name='Heures du vendredi'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='heures_a_prester',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Emploi du temps hebdomadaire × nombre de jours travaillés du mois.', max_digits=8, null=True, verbose_name='Heures à prester'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='heures_absence',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Heures non prestées retirées des heures à prester.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Heures d'absence"),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='imputation_sanctions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Jours chômés × imputation par jour chômé des paramètres de paie.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Imputation liée aux sanctions'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='jours_chomes',
            field=models.PositiveIntegerField(default=0, help_text='Absences non justifiées du mois (jours travaillés = jours ouvrables - jours chômés).', verbose_name='Jours chômés'),
        ),
        migrations.AddField(
            model_name='parametrepaie',
            name='retenue_par_jour_chome',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Sanction retenue pour chaque jour chômé (absence non justifiée), ex. 30 000 GNF.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Imputation par jour chômé (GNF)'),
        ),
        migrations.AddField(
            model_name='periodesalaire',
            name='nb_jeudis',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(6)], verbose_name='Nombre de jeudis travaillés'),
        ),
        migrations.AddField(
            model_name='periodesalaire',
            name='nb_lundis',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(6)], verbose_name='Nombre de lundis travaillés'),
        ),
        migrations.AddField(
            model_name='periodesalaire',
            name='nb_mardis',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(6)], verbose_name='Nombre de mardis travaillés'),
        ),
        migrations.AddField(
            model_name='periodesalaire',
            name='nb_mercredis',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(6)], verbose_name='Nombre de mercredis travaillés'),
        ),
        migrations.AddField(
            model_name='periodesalaire',
            name='nb_samedis',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(6)], verbose_name='Nombre de samedis travaillés'),
        ),
        migrations.AddField(
            model_name='periodesalaire',
            name='nb_vendredis',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(6)], verbose_name='Nombre de vendredis travaillés'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='mode_calcul_horaire',
            field=models.CharField(choices=[('POINTAGE', 'Pointage arrivée / départ'), ('MENSUEL', 'Total mensuel global'), ('MANUEL', "Saisie manuelle sur l'état"), ('HEBDO', 'Emploi du temps hebdomadaire (L à S)')], default='POINTAGE', help_text='Pour le secondaire : utiliser les pointages quotidiens ou un total mensuel saisi globalement.', max_length=10, verbose_name='Mode de calcul des heures'),
        ),
        migrations.AlterField(
            model_name='etatsalaire',
            name='mode_calcul_heures',
            field=models.CharField(blank=True, choices=[('POINTAGE', 'Pointage arrivée / départ'), ('MENSUEL', 'Total mensuel global'), ('MANUEL', "Saisie manuelle sur l'état"), ('HEBDO', 'Emploi du temps hebdomadaire (L à S)')], default='', help_text="Mode conservé au moment du calcul pour l'historique", max_length=10, verbose_name='Source des heures'),
        ),
    ]
