# Generated by Django 5.2.6 on 2026-08-27 14:06

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_add_sync_tracking'),
        ('eleves', '0017_alter_classe_niveau_alter_grilletarifaire_niveau'),
        ('paiements', '0012_isoler_paiements_par_annee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnementbus',
            name='annee_scolaire',
            field=models.CharField(blank=True, db_index=True, max_length=9, validators=[django.core.validators.RegexValidator(message="L'année scolaire doit être au format AAAA-AAAA.", regex='^\\d{4}-\\d{4}$')], verbose_name='Année scolaire'),
        ),
        migrations.AddField(
            model_name='abonnementbus',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_bus_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abonnementbus',
            name='mode_paiement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements_bus', to='paiements.modepaiement', verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='abonnementbus',
            name='numero_recu',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Numéro de reçu'),
        ),
        migrations.CreateModel(
            name='GrilleTarifaireBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
                ('sync_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('zone', models.CharField(help_text='Exemple : Ratoma, Sonfonia ou Circuit A.', max_length=100, verbose_name='Zone / circuit')),
                ('annee_scolaire', models.CharField(db_index=True, max_length=9, validators=[django.core.validators.RegexValidator(message="L'année scolaire doit être au format AAAA-AAAA.", regex='^\\d{4}-\\d{4}$')], verbose_name='Année scolaire')),
                ('tranche_1', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='1ère tranche (GNF)')),
                ('tranche_2', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='2ème tranche (GNF)')),
                ('tranche_3', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='3ème tranche (GNF)')),
                ('date_echeance_tranche_1', models.DateField(blank=True, null=True, verbose_name='Échéance de la 1ère tranche')),
                ('date_echeance_tranche_2', models.DateField(blank=True, null=True, verbose_name='Échéance de la 2ème tranche')),
                ('date_echeance_tranche_3', models.DateField(blank=True, null=True, verbose_name='Échéance de la 3ème tranche')),
                ('actif', models.BooleanField(db_index=True, default=True, verbose_name='Grille active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grilles_bus_creees', to=settings.AUTH_USER_MODEL)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grilles_tarifaires_bus', to='eleves.ecole')),
            ],
            options={
                'verbose_name': 'Grille tarifaire bus',
                'verbose_name_plural': 'Grilles tarifaires bus',
                'ordering': ['-annee_scolaire', 'zone'],
            },
        ),
        migrations.AddField(
            model_name='abonnementbus',
            name='grille',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versements', to='bus.grilletarifairebus', verbose_name='Grille tarifaire'),
        ),
        migrations.AddIndex(
            model_name='abonnementbus',
            index=models.Index(fields=['eleve', 'grille', 'periodicite'], name='bus_abonnem_eleve_i_3da649_idx'),
        ),
        migrations.AddIndex(
            model_name='grilletarifairebus',
            index=models.Index(fields=['ecole', 'annee_scolaire', 'actif'], name='bus_grillet_ecole_i_9e262d_idx'),
        ),
        migrations.AddConstraint(
            model_name='grilletarifairebus',
            constraint=models.UniqueConstraint(fields=('ecole', 'zone', 'annee_scolaire'), name='bus_grille_unique_ecole_zone_annee'),
        ),
    ]
