# Generated by Django 5.2.6 on 2026-08-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0006_abonnement_references_externes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnementbus',
            name='periodicite',
            field=models.CharField(choices=[('MENSUEL', 'Mensuel'), ('ANNUEL', 'Annuel'), ('T1', '1ère Tranche'), ('T2', '2ème Tranche'), ('T3', '3ème Tranche')], default='MENSUEL', help_text='Choisissez Annuel pour régler la totalité des trois tranches.', max_length=10, verbose_name='Type de paiement / périodicité'),
        ),
        migrations.AlterField(
            model_name='abonnementcantine',
            name='periodicite',
            field=models.CharField(choices=[('JOURNALIER', 'Journalier'), ('HEBDOMADAIRE', 'Hebdomadaire'), ('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('ANNUEL', 'Annuel')], default='MENSUEL', max_length=15, verbose_name='Type de paiement / périodicité'),
        ),
        migrations.AlterField(
            model_name='abonnementcantine',
            name='type_repas',
            field=models.CharField(choices=[('DEJEUNER', 'Déjeuner uniquement'), ('GOUTER', 'Goûter uniquement'), ('COMPLET', 'Déjeuner + Goûter'), ('REPAS_10H', 'Repas de 10 h'), ('REPAS_14H', 'Repas de 14 h'), ('REPAS_10H_14H', 'Repas de 10 h + 14 h')], default='DEJEUNER', help_text="Créneau de repas choisi pour l'élève.", max_length=20, verbose_name='Type ou horaire du repas'),
        ),
    ]
